manifest:
  remotes:
    - name: electronshepherds
      url-base: https://github.com/electronshepherds
  projects:
    - name: zephyr
      remote: electronshepherds
      revision: v2.2.0
      import: true
  self:
    path: app
