manifest:
  remotes:
    - name: es
      url-base: https://github.com/electronshepherds
  projects:
    - name: zephyr
      remote: es
      revision: develop
      import: true
  self:
    path: app
