manifest:
  remotes:
    - name: electronshepherds
      url-base: https://gitlab.com/electronshepherds
  projects:
    - name: zephyr
      remote: electronshepherds
      revision: master
      import: true
  self:
    path: app
